drw_entities: add missing return in DRW_Tolerance::parseCode()
The below commit added DRW_Tolerance::parseCode() without actually
returning anything from all except the default case. Return `true` in
that case.

The compiler correctly complains:
```
src/drw_entities.cpp:1165:1: error: control reaches end of non-void function [-Werror=return-type]
```

Fixes: 944e6340fe5a (Ordinate Dimensions (#2131))